# Generated by Django 4.2.4 on 2023-08-30 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_currency', models.CharField(max_length=100)),
                ('to_currency', models.CharField(max_length=100)),
                ('amount', models.BigIntegerField()),
            ],
            options={
                'db_table': 'currency',
            },
        ),
    ]
