# Generated by Django 4.2.4 on 2023-08-31 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='from_currency',
            field=models.CharField(choices=[('AFN', 'Afghan afghani'), ('ALL', 'Albanian lek'), ('DZD', 'Algerian dinar'), ('ARS', 'Argentine peso\t'), ('AMD', 'Armenian dram')], max_length=100),
        ),
        migrations.AlterField(
            model_name='currency',
            name='to_currency',
            field=models.CharField(choices=[('AFN', 'Afghan afghani'), ('ALL', 'Albanian lek'), ('DZD', 'Algerian dinar'), ('ARS', 'Argentine peso\t'), ('AMD', 'Armenian dram')], max_length=100),
        ),
    ]
