# Generated by Django 4.2.4 on 2023-08-31 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0002_alter_currency_from_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='from_currency',
            field=models.CharField(choices=[('AFN', 'AFN'), ('ALL', 'ALL'), ('DZD', 'DZD'), ('ARS', 'ARS'), ('AMD', 'AMD'), ('AUD', 'AUD'), ('AZN', 'AZN'), ('BSD', 'BSD'), ('BHD', 'BHD'), ('BDT', 'BDT'), ('BBD', 'BBD'), ('BYN', 'BYN'), ('EUR', 'EUR'), ('BZD', 'BZD'), ('XOF', 'XOF'), ('BTN', 'BTN'), ('BOB', 'BOB'), ('BAM', 'BAM'), ('BWP', 'BWP'), ('BRL', 'BRL'), ('BND', 'BND'), ('BGN', 'BGN'), ('CAD', 'CAD'), ('XAF', 'XAF'), ('CNY', 'CNY'), ('COP', 'COP'), ('CRC', 'CRC'), ('CUP', 'CUP'), ('CZK', 'CZK'), ('CDF', 'CDF'), ('DKK', 'DKK'), ('USD', 'USD'), ('EGP', 'EGP'), ('HUF', 'HUF'), ('ISK', 'ISK'), ('INR', 'INR'), ('IDR', 'IDR'), ('IRR', 'IRR'), ('IQD', 'IQD'), ('ILS', 'ILS'), ('JPY', 'JPY'), ('KZT', 'KZT'), ('KPW', 'KPW'), ('KRW', 'KRW'), ('KGS', 'KGS'), ('LAK', 'LAK'), ('LRD', 'LRD'), ('MGA', 'MGA'), ('MYR', 'MYR'), ('MXN', 'MXN'), ('MAD', 'MAD'), ('NZD', 'NZD'), ('NGN', 'NGN'), ('NOK', 'NOK'), ('PKR', 'PKR'), ('ILS', 'ILS'), ('PYG', 'PYG'), ('PLN', 'PLN'), ('QAR', 'QAR'), ('RUB', 'RUB'), ('SAR', 'SAR'), ('XOF', 'XOF'), ('SEK', 'SEK'), ('CHF', 'CHF'), ('TJS', 'TJS'), ('THB', 'THB'), ('TRY', 'TRY'), ('TMT', 'TMT'), ('UAH', 'UAH'), ('AED', 'AED'), ('GBP', 'GBP'), ('UYU', 'UYU'), ('UZS', 'UZS'), ('VEF', 'VEF'), ('YER', 'YER')], db_column='from', max_length=100),
        ),
        migrations.AlterField(
            model_name='currency',
            name='to_currency',
            field=models.CharField(choices=[('AFN', 'AFN'), ('ALL', 'ALL'), ('DZD', 'DZD'), ('ARS', 'ARS'), ('AMD', 'AMD'), ('AUD', 'AUD'), ('AZN', 'AZN'), ('BSD', 'BSD'), ('BHD', 'BHD'), ('BDT', 'BDT'), ('BBD', 'BBD'), ('BYN', 'BYN'), ('EUR', 'EUR'), ('BZD', 'BZD'), ('XOF', 'XOF'), ('BTN', 'BTN'), ('BOB', 'BOB'), ('BAM', 'BAM'), ('BWP', 'BWP'), ('BRL', 'BRL'), ('BND', 'BND'), ('BGN', 'BGN'), ('CAD', 'CAD'), ('XAF', 'XAF'), ('CNY', 'CNY'), ('COP', 'COP'), ('CRC', 'CRC'), ('CUP', 'CUP'), ('CZK', 'CZK'), ('CDF', 'CDF'), ('DKK', 'DKK'), ('USD', 'USD'), ('EGP', 'EGP'), ('HUF', 'HUF'), ('ISK', 'ISK'), ('INR', 'INR'), ('IDR', 'IDR'), ('IRR', 'IRR'), ('IQD', 'IQD'), ('ILS', 'ILS'), ('JPY', 'JPY'), ('KZT', 'KZT'), ('KPW', 'KPW'), ('KRW', 'KRW'), ('KGS', 'KGS'), ('LAK', 'LAK'), ('LRD', 'LRD'), ('MGA', 'MGA'), ('MYR', 'MYR'), ('MXN', 'MXN'), ('MAD', 'MAD'), ('NZD', 'NZD'), ('NGN', 'NGN'), ('NOK', 'NOK'), ('PKR', 'PKR'), ('ILS', 'ILS'), ('PYG', 'PYG'), ('PLN', 'PLN'), ('QAR', 'QAR'), ('RUB', 'RUB'), ('SAR', 'SAR'), ('XOF', 'XOF'), ('SEK', 'SEK'), ('CHF', 'CHF'), ('TJS', 'TJS'), ('THB', 'THB'), ('TRY', 'TRY'), ('TMT', 'TMT'), ('UAH', 'UAH'), ('AED', 'AED'), ('GBP', 'GBP'), ('UYU', 'UYU'), ('UZS', 'UZS'), ('VEF', 'VEF'), ('YER', 'YER')], db_column='to', max_length=100),
        ),
    ]
